CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY,
 first_name VARCHAR(200) NOT NULL,
 last_name VARCHAR(255) NOT NULL,
 email VARCHAR(254) NOT NULL,
 password VARCHAR(255) NOT NULL,
 role VARCHAR(50) NOT NULL
);
CREATE SEQUENCE users_id_seq START WITH 3 INCREMENT BY 1;