name: Run tests on any Push event
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Install dependencies
        run: ./gradlew build
      - name: Test application
        run: ./gradlew test


