name: Run tests on any Push event
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: my_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 15432:5432
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Permission
        run: chmod +x gradlew
      - name: Install dependencies
        run: ./gradlew build
      - name: Test application
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:15432/postgres
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: my_password
        run: ./gradlew test


